name: golangci-lint

on: push

jobs:
  golangci:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: "1.16.6"
    - run: make deps
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29
