name: Publish Image

on:
  release:
    types: [created]

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          tgallant/db2jsonschema:${IMAGE_TAG}
          tgallant/db2jsonschema:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
